version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: kamel2022/backend:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
    command: gunicorn real_estate.wsgi:application --bind 0.0.0.0:8000
