# version: '3.8'

# services:
#   web:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "80:8000"
#     volumes:
#       - .:/app
#     environment:
#       - DEBUG=${DEBUG}
#       - SECRET_KEY=${SECRET_KEY}
#       - ALLOWED_HOSTS=${ALLOWED_HOSTS}

version: '3.8'

services:
  web:
    image: kamel2022/backend:latest
    ports:
      - "80:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
