version: '3.8'  # You can remove this line if you want to use the latest version without specifying it

services:
  web:
    build: .  # Points to the current directory where Dockerfile is located
    image: kamel2022/backend:latest
    ports:
      - "8000:8000"
    env_file:
      - /home/ubuntu/.env
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
