version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: kamel2022/backend:latest  # Change this if you're using Docker Hub or another registry
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    volumes:
      - .:/app
    restart: always
    command: gunicorn real_estate.wsgi:application --bind 0.0.0.0:8000